name: task_management_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom_navigation/
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAYBOLD.ttf
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.ttf
        - asset: assets/fonts/SFPRODISPLAYREGULAR.ttf
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.ttf

